def chorus():
    print("The ants go marching one by one, hurrah! hurrah!")
def verse(littleact):
    chorus()
    chorus()
    print("The ants go marching one by one,")
    print("The little one stops to" + littleact)
    print("And they go marching down...")
    print("In the ground...")
    print("To get out...")
    print("Of the rain.")
    print("Boom! Boom! Boom!")
def main():
    verse(" suck his thumb,")
    print()
    verse(" tie his shoe, ")
    print()
    verse(" dye her hair, ")
    print()
    verse(" dip her hip, ")
    print()
    verse(" lift his leg, ")
    print()
    verse(" hold her nose, ")
    print()
    verse(" fold his knee, ")
    print()
    verse(" fix his lips, ")
    print()
    verse(" clear her ear, ")
    print()
    verse(" bend his hand")
main()